name: Merge me test dependencies!

on:  # zizmor: ignore[dangerous-triggers] intentional: this workflow only evaluates completed checks
  workflow_run:
    types:
      - completed
    workflows:
      - 'Run tests'
      - 'Test build package'
      - 'Run pre-commit'
      - 'Run test commands'
  check_suite:
    types:
      - completed

permissions: {}

jobs:
  automerge:
    permissions: {}
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@3768ca868776ab12e78334cc376094a7aec3d9b6 # v5.3.1
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
