name: Merge me test dependencies!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Run tests'
      - 'Test build package'
      - 'Run pre-commit'
      - 'Run test commands'
  check_suite:
    types:
      - completed

jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@31be9bf07155154cfce850e9d4133b502ee6f023 # v5.3.0
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
