name: Merge me test dependencies!

on:
  pull_request:
    branches: [ main ]

jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@automerge-native-auto-merge
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
