name: Test build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@31be9bf07155154cfce850e9d4133b502ee6f023 # v5.3.0
