name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@v4.0.1
    with:
      python-versions: '["3.9", "3.10", "3.11", "3.12", "3.13"]'
