name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  tests:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@2ab3c94b032a11fca1238ef134690e589616739d # v5.7.0
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]'
      dependency-manager: 'uv'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
