name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  tests:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@bd825c06829614c809e87acac868a1143328a5b4 # v5.3.2
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]'
      dependency-manager: 'uv'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
