name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    uses: fizyk/actions-reuse/.github/workflows/tests-pytests.yml@v2.3.1
    with:
      pipenv-install-options: --skip-lock
      python-versions: '["3.8", "3.9", "3.10", "3.11"]'
