name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  tests:
    permissions:
      contents: read
    uses: fizyk/actions-reuse/.github/workflows/shared-tests-pytests.yml@7eefbd6ffc6c6787ad3be6ce93dcf475e3ae99b5 # v5.6.0
    with:
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]'
      dependency-manager: 'uv'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
